// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------------- //
// quaddec_encoder //
// --------------- //

#define quaddec_encoder_wrap_target 0
#define quaddec_encoder_wrap 2
#define quaddec_encoder_pio_version 0

static const uint16_t quaddec_encoder_program_instructions[] = {
            //     .wrap_target
    0x4002, //  0: in     pins, 2
    0x8000, //  1: push   noblock
    0x0000, //  2: jmp    0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program quaddec_encoder_program = {
    .instructions = quaddec_encoder_program_instructions,
    .length = 3,
    .origin = -1,
    .pio_version = quaddec_encoder_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config quaddec_encoder_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + quaddec_encoder_wrap_target, offset + quaddec_encoder_wrap);
    return c;
}
#endif

